[build]
  command = "pnpm prisma generate && pnpm build"
  publish = "dist/client"

[[redirects]]
  from = "https://ops-platform.netlify.app/*"
  to = "https://ops.posthog.dev/:splat"
  status = 301
  force = true
