name: Run scheduled jobs
on:
  schedule:
    - cron: '*/10 12 * * *' # every 10 minutes at 12:00 PM UTC
  workflow_dispatch:

jobs:
  runScheduledJobs:
    runs-on: ubuntu-latest
    steps:
      - name: Call runScheduledJobs endpoint
        id: runScheduledJobs
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ vars.BASE_URL }}/runScheduledJobs'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.SYNC_ENDPOINT_KEY }}"}'
          timeout: 30000
      - name: Show Response
        run: |
          echo ${{ steps.runScheduledJobs.outputs.status }}
          echo ${{ steps.runScheduledJobs.outputs.response }}
