name: Schedule check-ins
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  scheduleCheckIns:
    runs-on: ubuntu-latest
    steps:
      - name: Call scheduleCheckIns endpoint
        id: scheduleCheckIns
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ vars.BASE_URL }}/scheduleCheckIns'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.SYNC_ENDPOINT_KEY }}"}'
          timeout: 30000
      - name: Show Response
        run: |
          echo ${{ steps.scheduleCheckIns.outputs.status }}
          echo ${{ steps.scheduleCheckIns.outputs.response }}
